"""
Extracts the Bosc et al. 2021 MTB essentiality Excel file into individual CSVs, maps
nonessential_novi ORF IDs to UniProt accessions via the UniProt REST API, applies manual
curation for mismatches, and consolidates all essentiality categories into a master dataset
enriched with ChEMBL and known-target flags.

Inputs:
    data/raw/Bosc_etal_21_pebble.xlsx             — multi-sheet Excel file with MTB genes
                                                    grouped by essentiality category and
                                                    vulnerability index (VI) scores
                                                    (Bosc et al. 2021)
    data/processed/01_bosc2021/<sheet>.csv        — per-sheet CSVs with UniProt accessions;
                                                    all 12 are generated by this script
    data/processed/00_chembl/uniprot_ac_in_chembl.csv — UniProt accessions present in ChEMBL
                                                    for MTB (produced by
                                                    00_chembl_data_processing.py)
    data/raw/mtb_targets.csv                      — MANUALLY GENERATED: curated list of known
                                                    MTB drug targets; never overwritten

Outputs:
    data/raw/01_bosc_individual/<sheet>.csv        — one CSV per Excel sheet with standardised
                                                     column names and no empty columns; no
                                                     UniProt accessions (pure raw extraction)
    data/processed/01_bosc2021/nonessential_novi.csv — nonessential_novi sheet with UniProt
                                                     accessions added via API + manual curation
    data/processed/01_bosc2021/growthadvantage_novi.csv — updated with manual curation
    data/processed/01_bosc2021/uncertain_novi.csv       — updated with manual curation
    data/processed/01_bosc_uniprots.csv            — all 12 sheets joined into a single table
    data/processed/01_master_uniprots.csv          — bosc_uniprots enriched with in_chembl and
                                                     in_known flags, plus ChEMBL entries absent
                                                     from the Bosc dataset
"""

import os
import sys
root = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.join(root, "..", "src"))

import pandas as pd
import requests

raw_dir = os.path.join(root, "..", "data", "raw")
bosc_raw_dir = os.path.join(raw_dir, "01_bosc_individual")
processed_dir = os.path.join(root, "..", "data", "processed")
bosc_processed_dir = os.path.join(processed_dir, "01_bosc2021")
os.makedirs(bosc_raw_dir, exist_ok=True)
os.makedirs(bosc_processed_dir, exist_ok=True)

datasets = [
    "essential_novi",
    "essential_vi",
    "essentialdomain_novi",
    "essentialdomain_vi",
    "growthadvantage_novi",
    "growthadvantage_vi",
    "growthdefect_novi",
    "growthdefect_vi",
    "nonessential_vi",
    "nonessential_novi",
    "uncertain_novi",
    "uncertain_vi",
]

# Manual curation for ORFIDs in nonessential_novi that did not resolve via the UniProt API
nonessential_novi_manual = {
    "Rv1181": "A0A089QRB9",
    "Rv2922A": "P9WQC9",
    "Rv1369c": "P9WKH9",
    "Rv1370c": "P9WKH5",
    "Rv1756c": "P9WKH9",
    "Rv1757c": "P9WKH5",
    "Rv1763": "P9WKH5",
    "Rv1764": "P9WKH9",
    "Rv2105": "P9WKH5",
    "Rv2106": "P9WKH9",
    "Rv2167c": "P9WKH9",
    "Rv2168c": "P9WKH5",
    "Rv2278": "P9WKH5",
    "Rv2279": "P9WKH9",
    "Rv2307D": "L7N683",
    "Rv2354": "P9WKH5",
    "Rv2355": "P9WKH9",
    "Rv2479c": "P9WKH9",
    "Rv2480c": "P9WKH5",
    "Rv2512c": "P60230",
    "Rv2561": "P9WL99",
    "Rv2562": "P9WL99",
    "Rv2648": "P9WKH5",
    "Rv2649": "P9WKH9",
    "Rv2814c": "P9WKH9",
    "Rv2815c": "P9WKH5",
    "Rv3023c": "P96354",
    "Rv3115": "P96354",
    "Rv3184": "P9WKH5",
    "Rv3185": "P9WKH9",
    "Rv3186": "P9WKH5",
    "Rv3187": "P9WKH9",
    "Rv3325": "P9WKH5",
    "Rv3326": "P9WKH5",
    "Rv3380c": "P9WKH9",
    "Rv3381c": "P9WKH5",
    "Rv3467": "Q50655",
    "Rv3474": "P9WKH5",
    "Rv3475": "P9WKH9",
    "Rv3798": "P9WKH7",
    "Rv3844": "P96234",
}

# Manual curation for remaining sheets with sparse mismatches
growthadv_novi_manual = {"Rv0815c": "P9WHF9"}
uncertain_novi_manual = {"Rv3021c": "P9WHY7"}

# Manually assembled entries: ChEMBL targets not present in the Bosc dataset,
# assembled by hand from ChEMBL and UniProt lookups
missing_chembl_entries = {
    "Q50575":      [None,       "pncA",   "Nicotinamide deamidase",                                           None, None,     None, None, None, None, "Q50575",     1, 0],
    "A0A0H3M0T0":  [None,       "ptbB",   "Phosphotyrosine protein phosphatase ptpB",                         None, None,     None, None, None, None, "A0A0H3M0T0", 1, 0],
    "A5U6Z7":      ["MRA_3015", "hupB",   "DNA-binding protein HupB",                                         None, "Hr7Ra",  None, None, None, None, "A5U6Z7",     1, 0],
    "P9WKK6":      ["MT0483",   "icl1",   "Isocitrate lyase 1",                                               None, "CDC1551",None, None, None, None, "P9WKK6",     1, 0],
    "A0A045ISB3":  [None,       "iphP",   "Phosphotyrosine protein phosphatase",                              None, None,     None, None, None, None, "A0A045ISB3", 1, 0],
    "P96884":      [None,       "birA",   "biotin--[biotin carboxyl-carrier protein] ligase",                 None, None,     None, None, None, None, "P96884",     1, 0],
    "A5U4N0":      ["MRA_2218", "adoK",   "Adenosine kinase",                                                 None, "Hr7Ra",  None, None, None, None, "A5U4N0",     1, 0],
    "P95276":      ["MT1988",   None,     "Epoxide hydrolase B",                                              None, "CDC1551",None, None, None, None, "P95276",     1, 0],
    "P9WPS0":      ["MT1345",   "atpE",   "ATP synthase subunit c",                                           None, "CDC1551",None, None, None, None, "P9WPS0",     1, 0],
    "P9WH10":      ["MT3571",   "rmlC",   "dTDP-4-dehydrorhamnose 3,5-epimerase",                             None, "CDC1551",None, None, None, None, "P9WH10",     1, 0],
    "P96830":      ["MT0162",   None,     "Tyrosine specific protein phosphatases domain-containing protein", None, "CDC1551",None, None, None, None, "P96830",     1, 0],
    "P9WID4":      ["MT2258",   "adoK",   "Adenosine kinase",                                                 None, "CDC1551",None, None, None, None, "P9WID4",     1, 0],
    "A0A0T9WNE5":  [None,       "cyp121", "Cytochrome P450 MT2",                                              None, None,     None, None, None, None, "A0A0T9WNE5", 1, 0],
    "Q93SP7":      [None,       "pncA",   "Nicotinamide deamidase",                                           None, None,     None, None, None, None, "Q93SP7",     1, 0],
    "O69638":      ["MT3771",   None,     "Hydrolase, alpha/beta hydrolase fold family",                      None, None,     None, None, None, None, "O69638",     1, 0],
}


def uniprot_accession(gene):
    url = "https://rest.uniprot.org/uniprotkb/search"
    query = f"gene_exact:{gene} AND organism_id:83332"
    params = {"query": query, "format": "json", "size": 1}
    r = requests.get(url, params=params)
    r.raise_for_status()
    results = r.json().get("results", [])
    if results:
        if len(results) > 1:
            print(gene)
        uniprot_id = results[0]["primaryAccession"]
        try:
            orf_id = results[0]["genes"][0]["orderedLocusNames"][0]["value"]
        except Exception:
            uniprot_id = None
            orf_id = None
        return uniprot_id, orf_id
    return None, None


# --- Section 1: Extract Excel sheets to raw ---
# Resolves two Excel artefacts: stray empty columns (3 sheets) and duplicate VI
# column headers in essential_vi (pandas reads as VI.1/VI.2 → renamed to VI_lower/VI_higher)

dfs = pd.read_excel(os.path.join(raw_dir, "Bosc_etal_21_pebble.xlsx"), sheet_name=None)

for name, df in dfs.items():
    unnamed_cols = [c for c in df.columns if str(c).startswith("Unnamed")]
    if unnamed_cols:
        df = df.drop(columns=unnamed_cols)
    df = df.rename(columns={"VI.1": "VI_lower", "VI.2": "VI_higher"})
    df.to_csv(os.path.join(bosc_raw_dir, f"{name}.csv"), index=False)
    print(f"{name}: {df.shape[0]} rows, columns: {list(df.columns)}")

# --- Section 2: Map all sheet ORFIDs to UniProt via API ---
# Skips sheets whose output CSV already exists in 01_bosc2021/ to allow safe re-runs

for k in dfs.keys():
    out_path = os.path.join(bosc_processed_dir, f"{k}.csv")
    if os.path.exists(out_path):
        print(f"[{k}] already exists, skipping API calls")
        continue
    # Read the cleaned raw CSV so column names are already standardised
    df_sheet = pd.read_csv(os.path.join(bosc_raw_dir, f"{k}.csv"))
    uniprot_ids = []
    for gene in df_sheet["ORFID"].tolist():
        uniprot_id, orf_id = uniprot_accession(gene)
        if orf_id == gene:
            uniprot_ids += [uniprot_id]
        else:
            uniprot_ids += [None]
            print(f"[{k}] MISMATCH: query={gene}, orderedLocus={orf_id}, UniProt={uniprot_id}")
    df_sheet["uniprot_id"] = uniprot_ids
    df_sheet.to_csv(out_path, index=False)

# --- Section 3: Apply manual curation to fill remaining NaN uniprot_ids ---

df = pd.read_csv(os.path.join(bosc_processed_dir, "growthadvantage_novi.csv"))
df["uniprot_id"] = df["uniprot_id"].fillna(df["ORFID"].map(growthadv_novi_manual))
df.to_csv(os.path.join(bosc_processed_dir, "growthadvantage_novi.csv"), index=False)

df = pd.read_csv(os.path.join(bosc_processed_dir, "nonessential_novi.csv"))
df["uniprot_id"] = df["uniprot_id"].fillna(df["ORFID"].map(nonessential_novi_manual))
df.to_csv(os.path.join(bosc_processed_dir, "nonessential_novi.csv"), index=False)

df = pd.read_csv(os.path.join(bosc_processed_dir, "uncertain_novi.csv"))
df["uniprot_id"] = df["uniprot_id"].fillna(df["ORFID"].map(uncertain_novi_manual))
df.to_csv(os.path.join(bosc_processed_dir, "uncertain_novi.csv"), index=False)

# --- Section 4: Join all sheets, dropping rows without UniProt ID or VI score ---

dfs_list = []
for d in datasets:
    df = pd.read_csv(os.path.join(bosc_processed_dir, f"{d}.csv"))
    if "Unnamed: 9" in list(df.columns):
        df = df.drop(columns="Unnamed: 9")
        df = df[~df["VI"].astype(str).str.contains("Not Present.")]
    df = df[~df["uniprot_id"].isna()]
    df = df[~df["VI"].isna()]
    dfs_list += [df]

df = pd.concat(dfs_list)
df.to_csv(os.path.join(processed_dir, "01_bosc_uniprots.csv"), index=False)

# --- Section 5: Enrich with ChEMBL and known-target flags ---

chembl = pd.read_csv(os.path.join(processed_dir, "00_chembl", "uniprot_ac_in_chembl.csv"))
known = pd.read_csv(os.path.join(raw_dir, "mtb_targets.csv"))

in_chembl = set(chembl["uniprot_ac"].tolist())
in_known = set(known["uniprot_ac"].tolist())

df["in_chembl"] = [1 if x in in_chembl else 0 for x in df["uniprot_id"].tolist()]
df["in_known"] = [1 if x in in_known else 0 for x in df["uniprot_id"].tolist()]

# Append manually assembled ChEMBL entries absent from the Bosc dataset
cols = df.columns.tolist()

missing_df = pd.DataFrame.from_dict(missing_chembl_entries, orient="index")
missing_df = missing_df.reset_index(drop=True)
missing_df.columns = cols
df = pd.concat([df, missing_df])

df.to_csv(os.path.join(processed_dir, "01_master_uniprots.csv"), index=False)
